In [ ]:
import numpy as np
import pandas as pd

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

In [ ]:
df=pd.read_csv('gurgaon_properties_cleaned_v1.csv')

In [ ]:
df.head(1)
# focus is on -> areaWithType, additional room, agePossession, furnishDetails, features

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
0,house,independent,sector 4,3.25,14444.0,2250.0,Plot area 250(209.03 sq.m.),3,3,2,not available,2.0,South-East,10+ Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Prateek Nursing Home And Polyclinic', 'Kr Dental Hub', 'Jain Sant Phool Chand Ji Charitable Hospital', 'Sarvodya Hospital', 'Sneh Hospital Gurgaon', 'Shree Krishna Hospital Gurgaon', 'Dr. Ashok Jain', 'Gurgaon Eye Centre', 'Dr. Sindhu Clinic', 'Pearl Dental Clinic', 'Dr. Hitesh Dawar', 'Dr. Mittal Clinic', 'Jiya Clinic', 'Aryan Hospital', 'Yashroop Medical Centre', 'Taneja Hospital', ""Dr. Anurag's Child Care Clinic"", 'Esic Hospital Gurugram', 'D.R. Rajnis Gupta Clinic', 'Geeta Nursing Home Gurgaon', 'Sparsh Hospital Gurgaon', 'Bhardwaj Hospital', 'Ravi Clinic and Health Care Centre', 'Bhatnagar Maternity and Nursing Home', 'Chiranjiv Hospital', 'Dr. Agya Ram Sharma Clinic', 'GH Gurgaon', 'Dr. Madan Clinic', 'Bindal Clinic', 'Dr. Sarvejeet Singh', 'R K Hospital Gurgaon', 'Dev Man Kathuria Clinic', 'Swastik Maternity and Medical Centre', 'Centre For Sight Gurgaon New Railway Road', 'M.S Hospital', 'My Care Clinic', 'Kidney Clinic', 'Indian bank', 'Kotak bank', 'Hdfc bank', 'State bank of india', 'Pizza Hut', 'St. Michaels Sr. Sec. School', 'Dronacharya Government College', 'Gurgaon railway station', 'Gurgaon railway station', 'Gurgaon railway station']","['30 Light', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']","['Feng Shui / Vaastu Compliant', 'Park', 'Visitor Parking', 'Low Density Society']"

In [ ]:
df.shape

(3805, 17)

# 1.areaWithType

In [ ]:
df[['price','area','areaWithType']].sample(5)

,price,area,areaWithType
2855,1.10,1350.0,Built Up area: 1350 (125.42 sq.m.)Carpet area: 1050 sq.ft. (97.55 sq.m.)
1276,0.56,1364.0,Super Built up area 1364(126.72 sq.m.)
1448,3.50,2937.0,Built Up area: 2937 (272.86 sq.m.)Carpet area: 1762 sq.ft. (163.7 sq.m.)
1188,0.90,1780.0,Built Up area: 1780 (165.37 sq.m.)
2674,0.95,915.0,Built Up area: 915 (85.01 sq.m.)Carpet area: 858 sq.ft. (79.71 sq.m.)

In [ ]:
import re

In [ ]:
# Function to extract Super Built up area
def get_super_built_up_area(text):
  match=re.search(r'Super Built up area (\d+\.?\d*)',text)
  if match:
    return float(match.group(1))
  else:
    return None

In [ ]:
# Function to Built up area or Carpet area
def get_area(text,area_type):
  match=re.search(area_type + r'\s*:\s*(\d+\.?\d*)',text)
  if match:
    return float(match.group(1))
  else:
    return None

In [ ]:
# Function to check the unit, if it is in sq.m. it will cange to sqft
def conv_to_sqft(text,area_value):
  if area_value is None:
    return None
  match=re.search(r'{} \((\d+\.?\d*) sq.m.\)'.format(area_value), text)
  if match:
    sq_m_value = float(match.group(1))
    return sq_m_value * 10.7639  # conversion factor from sq.m. to sqft
  return area_value

In [ ]:
df['super_built_up_area']=df['areaWithType'].apply(get_super_built_up_area)
df['super_built_up_area']=df.apply(lambda x: conv_to_sqft(x['areaWithType'],x['super_built_up_area']),axis=1)

In [ ]:
df['built_up_area']=df['areaWithType'].apply(get_area,area_type='Built Up area')
df['built_up_area']=df.apply(lambda x: conv_to_sqft(x['areaWithType'],x['built_up_area']),axis=1)

In [ ]:
df['carpet_area']=df['areaWithType'].apply(get_area,area_type='Carpet area')
df['carpet_area']=df.apply(lambda x: conv_to_sqft(x['areaWithType'],x['carpet_area']),axis=1)

In [ ]:
df[['price','property_type','area','areaWithType','super_built_up_area','built_up_area','carpet_area']].sample(5)

,price,property_type,area,areaWithType,super_built_up_area,built_up_area,carpet_area
88,0.32,flat,585.0,Built Up area: 1000 (92.9 sq.m.)Carpet area: 585 sq.ft. (54.35 sq.m.),NaN,1000.0,585.0
3234,0.60,flat,790.0,Built Up area: 790 (73.39 sq.m.)Carpet area: 750 sq.ft. (69.68 sq.m.),NaN,790.0,750.0
824,2.35,flat,2775.0,Super Built up area 2598(241.36 sq.m.),2598.0,NaN,NaN
2594,5.75,house,3500.0,Plot area 272(25.27 sq.m.)Built Up area: 4800 sq.ft. (445.93 sq.m.)Carpet area: 3500 sq.ft. (325.16 sq.m.),NaN,4800.0,3500.0
790,0.40,flat,900.0,Carpet area: 900 (83.61 sq.m.),NaN,NaN,900.0

In [ ]:
df[~(df['super_built_up_area'].isnull()|df['built_up_area'].isnull()|df['carpet_area'].isnull())][['price','property_type','area','areaWithType','super_built_up_area','built_up_area','carpet_area']].shape

(534, 7)

In [ ]:
df[df['areaWithType'].str.contains('Plot')][['price','property_type','area','areaWithType','super_built_up_area','built_up_area','carpet_area']].shape

(682, 7)

In [ ]:
df.isnull().sum()

property_type             0
society                   1
sector                    0
price                    17
price_per_sqft           17
area                     17
areaWithType              0
bedRoom                   0
bathroom                  0
balcony                   0
additionalRoom            0
floorNum                 19
facing                 1105
agePossession             1
nearbyLocations         177
furnishDetails          980
features                638
super_built_up_area    1890
built_up_area          2615
carpet_area            1859
dtype: int64

In [ ]:
all_nan_df=df[(df['super_built_up_area'].isnull()) & (df['built_up_area'].isnull()) & (df['carpet_area'].isnull())][['price','property_type','area','areaWithType','super_built_up_area','built_up_area','carpet_area']]
all_nan_df.sample(5)

,price,property_type,area,areaWithType,super_built_up_area,built_up_area,carpet_area
624,0.50,house,900.0,Plot area 900(83.61 sq.m.),NaN,NaN,NaN
2514,3.71,house,1872.0,Plot area 208(173.91 sq.m.),NaN,NaN,NaN
3705,14.75,house,2844.0,Plot area 316(264.22 sq.m.),NaN,NaN,NaN
1938,7.10,house,251.0,Plot area 240(22.3 sq.m.),NaN,NaN,NaN
3739,3.40,house,2250.0,Plot area 250(209.03 sq.m.),NaN,NaN,NaN

In [ ]:
all_nan_df.shape

(546, 7)

In [ ]:
all_nan_index=all_nan_df.index

In [ ]:
#function to extract plot area from'areaWithType'
def extract_plot_area(text):
  match=re.search(r'Plot area (\d+\.?\d*)',text)
  return float(match.group(1)) if match else None

In [ ]:
all_nan_df['built_up_area']=all_nan_df['areaWithType'].apply(extract_plot_area)

In [ ]:
all_nan_df.sample(5)

,price,property_type,area,areaWithType,super_built_up_area,built_up_area,carpet_area
2129,17.00,house,4518.0,Plot area 502(419.74 sq.m.),NaN,502.0,NaN
3493,5.75,house,1935.0,Plot area 215(179.77 sq.m.),NaN,215.0,NaN
30,2.15,house,900.0,Plot area 100(83.61 sq.m.),NaN,100.0,NaN
72,2.25,house,900.0,Plot area 100(83.61 sq.m.),NaN,100.0,NaN
3710,5.50,house,1800.0,Plot area 200(167.23 sq.m.),NaN,200.0,NaN

In [ ]:
all_nan_df['built_up_area'].isnull().sum()

np.int64(0)

In [ ]:
def convert_scale(row):
  if np.isnan(row['area']) :
    return row['built_up_area']
  else:
    if round((row['area']/row['built_up_area'])) == 9.0 :
      return row['built_up_area']*9
    if round((row['area']/row['built_up_area'])) == 11.0 :
      return row['built_up_area']*10.7
    return row['built_up_area']

In [ ]:
all_nan_df['built_up_area']=all_nan_df.apply(convert_scale,axis=1)

In [ ]:
all_nan_df.sample(5)

,price,property_type,area,areaWithType,super_built_up_area,built_up_area,carpet_area
687,27.50,house,11286.0,Plot area 1254(1048.5 sq.m.),NaN,11286.0,NaN
2,6.75,house,6228.0,Plot area 692(578.6 sq.m.),NaN,6228.0,NaN
1632,4.45,house,2880.0,Plot area 320(267.56 sq.m.),NaN,2880.0,NaN
3766,13.50,house,3618.0,Plot area 402(336.12 sq.m.),NaN,3618.0,NaN
302,1.35,house,1350.0,Plot area 1350(125.42 sq.m.),NaN,1350.0,NaN

In [ ]:
df.update(all_nan_df)

# 2.additionalRoom

In [ ]:
df['additionalRoom'].value_counts()

additionalRoom
not available                                    1589
servant room                                      705
study room                                        250
others                                            225
pooja room                                        165
store room                                         99
study room,servant room                            99
pooja room,servant room                            82
pooja room,study room,servant room,store room      72
servant room,others                                60
pooja room,study room,servant room                 55
pooja room,study room,servant room,others          54
servant room,pooja room                            38
servant room,store room                            33
study room,others                                  29
pooja room,study room                              22
pooja room,others                                  17
pooja room,store room                              15
servant room,study room                            12
pooja room,store room,study room,servant room      12
study room,servant room,store room                 11
pooja room,servant room,others                     11
study room,pooja room                              10
servant room,study room,pooja room,store room      10
study room,servant room,pooja room,store room       8
store room,servant room                             8
pooja room,servant room,store room                  7
pooja room,study room,store room                    7
study room,pooja room,servant room                  7
study room,servant room,others                      7
others,servant room                                 6
servant room,pooja room,store room                  6
pooja room,servant room,study room,store room       5
study room,servant room,store room,pooja room       5
store room,pooja room                               5
servant room,store room,pooja room                  4
study room,pooja room,store room                    4
study room,servant room,pooja room                  4
pooja room,study room,others                        4
study room,pooja room,servant room,store room       3
pooja room,study room,store room,servant room       3
servant room,others,pooja room                      3
servant room,pooja room,study room,store room       3
servant room,study room,pooja room                  3
servant room,others,store room,pooja room           2
study room,pooja room,store room,servant room       2
servant room,study room,store room                  2
store room,pooja room,servant room                  2
study room,store room                               2
store room,pooja room,study room,servant room       2
store room,pooja room,study room                    2
servant room,store room,study room,pooja room       1
servant room,pooja room,study room                  1
pooja room,store room,servant room                  1
study room,others,servant room                      1
store room,pooja room,servant room,study room       1
store room,study room,servant room                  1
study room,store room,pooja room                    1
servant room,study room,store room,pooja room       1
servant room,study room,others                      1
store room,study room                               1
store room,servant room,study room,pooja room       1
others,study room                                   1
servant room,pooja room,store room,study room       1
store room,servant room,pooja room                  1
Name: count, dtype: int64

In [ ]:
new_cols=['study room','servant room','store room','pooja room','others']
for col in new_cols:
  df[col]=df['additionalRoom'].str.contains(col).astype(int)

In [ ]:
df[['additionalRoom','study room','servant room','store room','pooja room','others']].sample(5)

,additionalRoom,study room,servant room,store room,pooja room,others
271,not available,0,0,0,0,0
2282,not available,0,0,0,0,0
436,servant room,0,1,0,0,0
3143,"pooja room,study room,servant room,store room",1,1,1,1,0
3333,servant room,0,1,0,0,0

# 3.agePossessition

In [ ]:
df['agePossession'].value_counts()

agePossession
1 to 5 Year Old       1676
5 to 10 Year Old       575
0 to 1 Year Old        530
undefined              335
10+ Year Old           310
Under Construction      89
Within 6 months         70
Within 3 months         26
Dec-23                  20
By 2023                 19
By 2024                 17
Dec-24                  15
Mar-24                  14
Aug-23                   7
Dec-25                   7
Oct-24                   7
Jan-24                   7
Jun-24                   5
Nov-23                   5
By 2025                  4
Aug-24                   4
Jul-24                   4
Sep-23                   4
May-24                   3
Feb-24                   3
Oct-23                   3
Nov-24                   3
Jan-25                   3
Jun-27                   2
Mar-25                   2
Jan-26                   2
Sep-25                   2
Jun 2024                 2
Oct-25                   2
Jul-25                   2
Jul-27                   2
Dec 2023                 2
Dec-26                   2
By 2027                  2
Apr-26                   2
Aug-25                   2
Jun-25                   1
Jan-27                   1
Dec 2024                 1
Jan 2024                 1
Oct 2023                 1
Jul-26                   1
Nov-25                   1
Mar-26                   1
Oct 2024                 1
Aug-26                   1
Sep-27                   1
Apr-24                   1
Jan-28                   1
Name: count, dtype: int64

In [ ]:
def categorize_age_possession(value):
    if pd.isna(value):
        return "Undefined"
    if "0 to 1 Year Old" in value or "Within 6 months" in value or "Within 3 months" in value:
        return "New Property"
    if "1 to 5 Year Old" in value:
        return "Relatively New"
    if "5 to 10 Year Old" in value:
        return "Moderately Old"
    if "10+ Year Old" in value:
        return "Old Property"
    if "Under Construction" in value or "By" in value:
        return "Under Construction"
    try:
        # For entries like 'May 2024'
        int(value.split(" ")[-1])
        return "Under Construction"
    except:
        try:
          # For entries like 'Mar-2026'
          int(value.split("-")[-1])
          return "Under Construction"
        except:
          return "Undefined"

In [ ]:
df['agePossession']=df['agePossession'].apply(categorize_age_possession)

In [ ]:
df['agePossession'].value_counts()

agePossession
Relatively New        1676
New Property           626
Moderately Old         575
Undefined              336
Old Property           310
Under Construction     282
Name: count, dtype: int64

# 4.furnishDetails

In [ ]:
df.head()[['furnishDetails','features']]

,furnishDetails,features
0,"['30 Light', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']","['Feng Shui / Vaastu Compliant', 'Park', 'Visitor Parking', 'Low Density Society']"
1,"['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Geyser', '1 Stove', '10 Light', '1 Modular Kitchen', '4 AC', '1 Chimney', '1 Curtains', 'No Bed', 'No Dining Table', 'No Microwave', 'No Fridge', 'No Sofa', 'No TV', 'No Washing Machine', 'No Water Purifier']","['Centrally Air Conditioned', 'Security / Fire Alarm', 'Power Back-up', 'Feng Shui / Vaastu Compliant', 'Intercom Facility', 'Lift(s)', 'High Ceiling Height', 'Maintenance Staff', 'False Ceiling Lighting', 'Water Storage', 'Separate entry for servant room', 'No open drainage around', 'Piped-gas', 'Internet/wi-fi connectivity', 'Visitor Parking', 'Swimming Pool', 'Park', 'Natural Light', 'Airy Rooms', 'Spacious Interiors', 'Low Density Society', 'Waste Disposal', 'Rain Water Harvesting', 'Water softening plant', 'Shopping Centre', 'Fitness Centre / GYM', 'Club house / Community Center']"
2,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu Compliant', 'Private Garden / Terrace', 'Water purifier', 'Maintenance Staff', 'Water Storage', 'Separate entry for servant room', 'No open drainage around', 'Visitor Parking', 'Swimming Pool', 'Park', 'Security Personnel', 'Natural Light', 'Airy Rooms', 'Spacious Interiors', 'Low Density Society', 'Fitness Centre / GYM', 'Waste Disposal', 'Rain Water Harvesting', 'Club house / Community Center']"
3,"['1 Light', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']",NaN
4,"['1 Light', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']",NaN

In [ ]:
# Extract all furnishing
all_furnishings=[]
for detail in df['furnishDetails'].dropna():
  all_furnishings.extend(detail.replace('[','').replace(']','').replace("'","").split(', '))
all_furnishings=list(set(all_furnishings))
all_furnishings=all_furnishings[1:]
unique_furnishings=[]
for furnishing in all_furnishings:
  unique_furnishings.append(furnishing.split(' ')[1])
unique_furnishings=list(set(unique_furnishings))
unique_furnishings

['Chimney',
 'Fridge',
 'AC',
 'Dining',
 'Washing',
 'Stove',
 'Bed',
 'Geyser',
 'Water',
 'Fan',
 'TV',
 'Modular',
 'Wardrobe',
 'Microwave',
 'Light',
 'Exhaust',
 'Sofa',
 'Curtains']

In [ ]:
# Define a function to extract the count of a furnishing from the furnishDetails
def get_furnishing_count(details, furnishing):
    if pd.isna(furnish_details):
        return 0